(function(){
  const catalog=window.AI_ACTIVITY_CATALOG||[];
  const cfg=window.KA_AI_CONFIG||{};
  const baseDocumentHTML=documentHTML;
  const selected=new Set();
  function close(){document.querySelector('.ai-modal')?.remove()}
  function addButtons(){const box=document.querySelector('.header-actions')||document.querySelector('header>div:last-child');if(!box||document.getElementById('ai-generate'))return;const lib=document.createElement('button');lib.id='ai-library';lib.className='catalog-button';lib.textContent='▦ Расширенная библиотека';lib.onclick=openCatalog;const gen=document.createElement('button');gen.id='ai-generate';gen.className='ai-button';gen.textContent='✨ Создать содержание с ИИ';gen.onclick=openGenerate;box.prepend(gen);box.prepend(lib)}
  function compatible(a){return a.compatible_phase_ids?.includes(active)&&(a.compatible_type_ids?.includes(type)||!a.compatible_type_ids?.length)&&(a.compatible_form_ids?.includes(form)||!a.compatible_form_ids?.length)}
  function addActivity(a){const s=stages.find(x=>x.id===active);if(!s)return;s.blocks.push({id:uid(),sourceId:a.id,title:a.title,min:a.minutes||7,teacher:'Будет создано ИИ по паспорту выбранного урока.',students:'Будет создано ИИ по паспорту выбранного урока.',instruction:`Подготовить тематическую реализацию механики «${a.title}».`,example:'Будет создан законченный тематический образец.',materials:a.materials_hint||'определит ИИ',support:'Будет создано ИИ.',challenge:'Будет создано ИИ.',criterion:'Будет создан наблюдаемый критерий.',mode:a.mode||'определит ИИ',aiPending:true});selected.add(a.id);render();openCatalog()}
  function openCatalog(){close();const families=[...new Map(catalog.map(a=>[a.family_id,a.family_label||a.family_id]))];const m=document.createElement('div');m.className='ai-modal';m.innerHTML=`<section class="ai-panel"><div class="ai-panel-head"><div><small>232 МЕТОДИЧЕСКИЕ МЕХАНИКИ</small><h2>Расширенная библиотека Activities</h2></div><button>×</button></div><div class="ai-filters"><input id="ai-search" placeholder="Найти игру, проект, диалог, коррекцию…"><select id="ai-family"><option value="">Все семейства</option>${families.map(x=>`<option value="${x[0]}">${x[1]}</option>`).join('')}</select></div><div class="ai-list"></div><div class="ai-footer"><span>Активный этап: <b>${active}</b> · выбрано дополнительно: <b>${selected.size}</b></span><button class="gold" id="ai-finish">Вернуться к уроку</button></div></section>`;m.querySelector('.ai-panel-head button').onclick=close;m.querySelector('#ai-finish').onclick=close;document.body.append(m);const draw=()=>{const q=m.querySelector('#ai-search').value.toLowerCase(),fam=m.querySelector('#ai-family').value;const list=catalog.filter(a=>(!fam||a.family_id===fam)&&(!q||(a.title+' '+a.purpose+' '+a.mechanic).toLowerCase().includes(q))).sort((a,b)=>Number(compatible(b))-Number(compatible(a))).slice(0,120);m.querySelector('.ai-list').innerHTML=list.map(a=>`<article class="ai-card ${compatible(a)?'recommended':''}"><small>${a.family_label||a.family_id} · ${a.minutes||'?'} мин ${compatible(a)?'· РЕКОМЕНДОВАНО':''}</small><h3>${esc(a.title)}</h3><p>${esc(a.purpose)}</p><button data-id="${a.id}" class="${selected.has(a.id)?'added':''}">${selected.has(a.id)?'✓ Добавлено':`＋ Добавить в ${active}`}</button></article>`).join('');m.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{if(!selected.has(b.dataset.id))addActivity(catalog.find(a=>a.id===b.dataset.id))})};m.querySelector('#ai-search').oninput=draw;m.querySelector('#ai-family').onchange=draw;draw()}
  function payload(wishes){return{project_code:cfg.PROJECT_CODE,lesson:{id:lesson.id,legacy_id:lesson.legacy_id,module_title:lesson.module_title,section_title:lesson.section_title,ktp_topic:lesson.ktp_topic,focus:lesson.focus,grammar_focus:lesson.grammar_focus,skills:lesson.skills,product:lesson.product,lexical_bank:lesson.lexical_bank,functional_frames:lesson.functional_frames,micro_situation:lesson.micro_situation},type:{id:type,title:name(TYPES,type)},form:{id:form,title:name(FORMS,form)},stages:stages.map(s=>({phase_id:s.id,title:s.title,purpose:s.purpose,blocks:s.blocks.map(b=>{const a=catalog.find(x=>x.id===(b.sourceId||b.activityId));return{activity_id:b.sourceId||b.activityId||'CUSTOM',title:b.title,minutes:b.min,mode:b.mode,mechanic:a?.mechanic||b.instruction,ai_rules:a?.ai_rules||[]}})})),teacher_wishes:wishes||''}}
  function applyResult(r){stages=r.stages.map(s=>({id:s.phase_id,title:s.title,purpose:s.purpose,blocks:s.blocks.map(b=>({id:uid(),sourceId:b.activity_id,title:b.title,min:b.minutes,teacher:b.teacher_actions,students:b.student_actions,instruction:b.student_instruction,example:b.full_example,materials:b.materials,support:b.support,challenge:b.challenge,criterion:b.criterion,mode:b.mode,language_bank:b.language_bank,language_frames:b.language_frames}))}));window.KA_AI_HOMEWORK=r.homework;render()}
  function aiHomework(){const hw=window.KA_AI_HOMEWORK;return`<div class="document">${head(`Домашнее задание: ${lesson.ktp_topic}`)}<div class="docblock"><p><b>Для ученика:</b> выбери один вариант и проверь результат по указанным критериям.</p></div>${hw.map(h=>`<section class="homework-option"><h2>Вариант ${h.variant} · ${esc(h.title)} <small>${esc(h.time)}</small></h2><p class="situation"><b>Ситуация:</b> ${esc(h.situation)}</p><h3>Делай по шагам</h3><ol>${h.steps.map(x=>`<li>${esc(x)}</li>`).join('')}</ol><div class="bank"><b>Банк слов и идей:</b><br>${h.language_bank.map(esc).join(' · ')}</div><p><b>Полезные фразы:</b> ${h.language_frames.map(esc).join(' · ')}</p><div class="example"><b>Полный пример:</b><br>${esc(h.full_example)}</div><p><b>Что сдать:</b> ${esc(h.deliverable)}</p><div class="selfcheck"><b>Проверь себя</b>${h.self_check.map(x=>`<span>□ ${esc(x)}</span>`).join('')}</div></section>`).join('')}</div>`}
  function openGenerate(){close();const m=document.createElement('div');m.className='ai-modal';m.innerHTML=`<section class="ai-generate-panel"><button class="ai-close" aria-label="Закрыть">×</button><small class="eyebrow">AI-МЕТОДИСТ</small><h2>Создать тематическое содержание</h2><p>Выбранные этапы, продолжительность и Activities останутся неизменными. ИИ создаст инструкции, образцы, опоры, критерии и пять вариантов ДЗ для <b>${esc(lesson.legacy_id)} · ${esc(lesson.ktp_topic)}</b>.</p><label class="ai-wishes">Дополнительные пожелания учителя<textarea id="ai-wishes" placeholder="Например: слабый класс; больше устной практики; без цифровых инструментов"></textarea></label><div class="ai-status">${cfg.API_BASE?'Готово к генерации. Продолжительность и состав урока определяет учитель.':'Сервер ИИ пока не подключён.'}</div><div class="ai-result-docs" hidden></div><div class="ai-actions"><button id="ai-cancel">Отмена</button><button class="primary" id="ai-run">✨ Создать урок</button></div></section>`;m.querySelector('.ai-close').onclick=close;m.querySelector('#ai-cancel').onclick=close;m.querySelector('#ai-run').onclick=async()=>{const status=m.querySelector('.ai-status'),run=m.querySelector('#ai-run');if(!cfg.API_BASE){status.className='ai-status error';status.textContent='Сервер ИИ не подключён.';return}status.className='ai-status';status.textContent='ИИ создаёт выбранные элементы и проверяет техническую полноту…';run.disabled=true;try{const r=await fetch(cfg.API_BASE.replace(/\/$/,'')+(cfg.GENERATE_PATH||'/generate'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload(m.querySelector('#ai-wishes').value))});const data=await r.json();if(!r.ok||!data.result)throw Error(data.error||'Сервер не вернул урок');if(!data.qa?.ok)throw Error('Не удалось полностью заполнить материал: '+(data.qa?.errors||[]).join('; '));applyResult(data.result);status.className='ai-status success';status.innerHTML='<b>Урок создан.</b> Выберите документ для просмотра, печати или сохранения в PDF.';const docs=m.querySelector('.ai-result-docs');docs.hidden=false;docs.innerHTML=`<div><b>Карта урока</b><button data-doc="map">Предпросмотр</button></div><div><b>Конспект урока</b><button data-doc="outline">Предпросмотр</button></div><div><b>Домашнее задание</b><button data-doc="learner">Предпросмотр</button></div>`;docs.querySelectorAll('[data-doc]').forEach(b=>b.onclick=()=>window.openDocument(b.dataset.doc));m.querySelector('#ai-cancel').remove();run.textContent='Создать заново';run.disabled=false}catch(e){status.className='ai-status error';status.textContent='Ошибка: '+e.message;run.disabled=false}};document.body.append(m)}
  documentHTML=function(){if(tab==='learner'&&Array.isArray(window.KA_AI_HOMEWORK))return aiHomework();return baseDocumentHTML()};
  window.KA_AI={openCatalog,openGenerate,payload};addButtons();
})();
